language: haskell
ghc:
  - 7.0
  - 7.4
  - 7.6
  - 7.8
os:
  - linux
  - osx
notifications:
  email: false
  irc: "chat.freenode.net#hatex"
before_script:
  - cabal sdist
  - mkdir travisbuild
  - mv dist/HaTeX*.tar.gz travisbuild/HaTeX.tar.gz
  - cd travisbuild
  - tar xzvf HaTeX.tar.gz
  - cd HaTeX*
script:
  - cabal configure --enable-tests --ghc-option=-Werror
  - cabal build
  - cabal test
